# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1b2e95fc364982c4a2a43a077c489c87d1fa168742dde8374833ed8df65a4be0554486dd128098bcf62d72ee8872c0c6c3e73dda9528d300a76f003398f92537

test:
  secret_key_base: 1fbef17871008ea8530663e7914d52cbaa083c4511df2a7f4aa4df4d964f948417b0e5e058379dbbd39987ac799d8c3700097da653e9d50985cb3e4bf1a2ce4f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
